version: '3.8'

services:
  people-counting:
    image: harbor.tado.vn/long_dev/people_counting:latest
    container_name: people_counting
    network_mode: "host"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - HOST=0.0.0.0
      - PORT=8000
      - API_URL=https://api-dev.tado.vn/api/camera-statistics
      - SESSION_TOKEN=359c8b594fe339f1d7b8337ad22f4ac1
      - MODEL_PATH=app/weights/yolo_best3.pt
      - CONF=0.5
      - LD_LIBRARY_PATH=/usr/local/lib/python3.10/site-packages/NetSDK/Libs/linux64:/app_root/app/services/sdk/dist
    volumes:
      - ./app:/app_root/app
      - ./libplay.so:/usr/local/lib/python3.10/site-packages/NetSDK/Libs/linux64/libplay.so
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 3
