syntax = "proto3";

package yolo_person;

message DetectRequest {
  bytes image = 1;
  int32 resized_width = 2;
  int32 resized_height = 3;
  int32 orig_width = 4;
  int32 orig_height = 5;
  repeated int32 allowed_classes = 6;
}

message BoundingBox {
  int32 x1 = 1;
  int32 y1 = 2;
  int32 x2 = 3;
  int32 y2 = 4;
  float confidence = 5;
  string class_name = 6;
}

message DetectResponse {
  repeated BoundingBox bboxes = 1;
}

service YoloService {
  rpc DetectFrame (DetectRequest) returns (DetectResponse);
}
