# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yolo_det_vehicle.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'yolo_det_vehicle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16yolo_det_vehicle.proto\x12\x0cyolo_vehicle\"\x8f\x01\n\rDetectRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x15\n\rresized_width\x18\x02 \x01(\x05\x12\x16\n\x0eresized_height\x18\x03 \x01(\x05\x12\x12\n\norig_width\x18\x04 \x01(\x05\x12\x13\n\x0borig_height\x18\x05 \x01(\x05\x12\x17\n\x0f\x61llowed_classes\x18\x06 \x03(\x05\"e\n\x0b\x42oundingBox\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02y1\x18\x02 \x01(\x05\x12\n\n\x02x2\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x12\n\nclass_name\x18\x06 \x01(\t\";\n\x0e\x44\x65tectResponse\x12)\n\x06\x62\x62oxes\x18\x01 \x03(\x0b\x32\x19.yolo_vehicle.BoundingBox2W\n\x0bYoloService\x12H\n\x0b\x44\x65tectFrame\x12\x1b.yolo_vehicle.DetectRequest\x1a\x1c.yolo_vehicle.DetectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_det_vehicle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTREQUEST']._serialized_start=41
  _globals['_DETECTREQUEST']._serialized_end=184
  _globals['_BOUNDINGBOX']._serialized_start=186
  _globals['_BOUNDINGBOX']._serialized_end=287
  _globals['_DETECTRESPONSE']._serialized_start=289
  _globals['_DETECTRESPONSE']._serialized_end=348
  _globals['_YOLOSERVICE']._serialized_start=350
  _globals['_YOLOSERVICE']._serialized_end=437
# @@protoc_insertion_point(module_scope)
